name: Trufflehog Scan

on:
  pull_request:
    branches:
      - main

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Trufflehog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: '.'
          base: 'main'
          head: 'HEAD'
          extra_args: '--regex --entropy=False --max_depth 50'
